In [1]:
#importing libraries
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

import warnings
warnings.filterwarnings("ignore")

In [5]:
from google.colab import files
uploaded = files.upload()

Saving student-por (1).csv to student-por (1).csv

In [6]:
df = pd.read_csv("student-por (1).csv")
df

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,4,0,11,11
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,2,9,11,11
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,6,12,13,12
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,0,14,14,14
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,0,11,13,13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
644,MS,F,19,R,GT3,T,2,3,services,other,...,5,4,2,1,2,5,4,10,11,10
645,MS,F,18,U,LE3,T,3,1,teacher,services,...,4,3,4,1,1,1,4,15,15,16
646,MS,F,18,U,GT3,T,1,1,other,other,...,1,1,1,1,1,5,6,11,12,9
647,MS,M,17,U,LE3,T,3,1,services,services,...,2,4,5,3,4,2,6,10,10,10
648,MS,M,18,R,LE3,T,3,2,services,other,...,4,4,1,3,4,5,4,10,11,11

In [7]:
df.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,4,0,11,11
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,2,9,11,11
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,6,12,13,12
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,0,14,14,14
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,0,11,13,13

In [8]:
df.shape

(649, 33)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 649 entries, 0 to 648
Data columns (total 33 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   school      649 non-null    object
 1   sex         649 non-null    object
 2   age         649 non-null    int64
 3   address     649 non-null    object
 4   famsize     649 non-null    object
 5   Pstatus     649 non-null    object
 6   Medu        649 non-null    int64
 7   Fedu        649 non-null    int64
 8   Mjob        649 non-null    object
 9   Fjob        649 non-null    object
 10  reason      649 non-null    object
 11  guardian    649 non-null    object
 12  traveltime  649 non-null    int64
 13  studytime   649 non-null    int64
 14  failures    649 non-null    int64
 15  schoolsup   649 non-null    object
 16  famsup      649 non-null    object
 17  paid        649 non-null    object
 18  activities  649 non-null    object
 19  nursery     649 non-null    object
 20  higher      649 non-null    object
 21  internet    649 non-null    object
 22  romantic    649 non-null    object
 23  famrel      649 non-null    int64
 24  freetime    649 non-null    int64
 25  goout       649 non-null    int64
 26  Dalc        649 non-null    int64
 27  Walc        649 non-null    int64
 28  health      649 non-null    int64
 29  absences    649 non-null    int64
 30  G1          649 non-null    int64
 31  G2          649 non-null    int64
 32  G3          649 non-null    int64
dtypes: int64(16), object(17)
memory usage: 167.4+ KB

In [10]:
x = df.drop("G3" , axis = 1)

In [11]:
y = df["G3"]

In [12]:
#Verify feature set
#confirms that x contain only features and y contains only the target

#"I checked the head of x and y separately to ensure that the target variable was not accidently included in the feature set, preventing data leakage"
x.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,romantic,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,no,4,3,4,1,1,3,4,0,11
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,no,5,3,3,1,1,3,2,9,11
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,no,4,3,2,2,3,3,6,12,13
3,GP,F,15,U,GT3,T,4,2,health,services,...,yes,3,2,2,1,1,5,0,14,14
4,GP,F,16,U,GT3,T,3,3,other,other,...,no,4,3,2,1,2,5,0,11,13

In [13]:
y.head()

0    11
1    11
2    12
3    14
4    13
Name: G3, dtype: int64

In [14]:
x.shape,y.shape

((649, 32), (649,))

In [15]:
#checking data types after encoding
#it shows data types of all featres and confirms success

#“I verified that all categorical variables were converted into numerical form
# because machine learning models cannot work with object data types.”


x.dtypes

school        object
sex           object
age            int64
address       object
famsize       object
Pstatus       object
Medu           int64
Fedu           int64
Mjob          object
Fjob          object
reason        object
guardian      object
traveltime     int64
studytime      int64
failures       int64
schoolsup     object
famsup        object
paid          object
activities    object
nursery       object
higher        object
internet      object
romantic      object
famrel         int64
freetime       int64
goout          int64
Dalc           int64
Walc           int64
health         int64
absences       int64
G1             int64
G2             int64
dtype: object

In [16]:
#“I checked for remaining categorical features by selecting object-type
# columns to ensure the dataset was fully numeric before model training.”

x.select_dtypes(include="object").columns

Index(['school', 'sex', 'address', 'famsize', 'Pstatus', 'Mjob', 'Fjob',
       'reason', 'guardian', 'schoolsup', 'famsup', 'paid', 'activities',
       'nursery', 'higher', 'internet', 'romantic'],
      dtype='object')

In [17]:
#“The dataset contained multiple categorical features such as gender,
# school type, parental job, and support systems. I applied one-hot encoding
# to convert them into numerical form and dropped the first category to prevent multicollinearity.”

#ONE HOT ENCODING converts categorical data into numerical data so that machine learning could understand it

x = pd.get_dummies(x, drop_first=True)

In [18]:
#verifying
x.dtypes

age                  int64
Medu                 int64
Fedu                 int64
traveltime           int64
studytime            int64
failures             int64
famrel               int64
freetime             int64
goout                int64
Dalc                 int64
Walc                 int64
health               int64
absences             int64
G1                   int64
G2                   int64
school_MS             bool
sex_M                 bool
address_U             bool
famsize_LE3           bool
Pstatus_T             bool
Mjob_health           bool
Mjob_other            bool
Mjob_services         bool
Mjob_teacher          bool
Fjob_health           bool
Fjob_other            bool
Fjob_services         bool
Fjob_teacher          bool
reason_home           bool
reason_other          bool
reason_reputation     bool
guardian_mother       bool
guardian_other        bool
schoolsup_yes         bool
famsup_yes            bool
paid_yes              bool
activities_yes        bool
nursery_yes           bool
higher_yes            bool
internet_yes          bool
romantic_yes          bool
dtype: object

In [19]:
#“After one-hot encoding, some features appeared as boolean values. Since boolean features are natively supported by scikit-learn and represent binary information,
# I retained them without further conversion.”
y.dtype

dtype('int64')

In [20]:
#train test split
from sklearn.model_selection import train_test_split # This function splits the dataset into training and testing parts.Model should learn from one part Model should be tested on unseen data

In [21]:
x_train , x_test , y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=42)

#20% data → testing , 80% data → training
#random_state=42 Fixes randomness Ensures same split every time

#Question and answers

 Q1: Why do we split the data?

Answer: To evaluate how well the model performs on unseen data and avoid overfitting.

Q2: What happens if we don’t split?

Answer: The model may memorize the data, giving misleading performance metrics.

Why not 90–10 or 70–30?

Answer: 80–20 is a balanced and commonly accepted split that works well for medium-sized datasets.

Q4: What is overfitting?

Answer: When a model performs well on training data but poorly on new data.

In [22]:
#SCALING = FAIRNESS OF FEATURES
#FEATURE SCALING = iska mtlb sare features ko ek level pr lana
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()  #Data ko is form mein laata hai: Mean = 0 Std = 1 Isse: Bade numbers chhote ho jaate hain Chhote numbers bade ho jaate hain

In [23]:
#fit → training data ka mean aur std seekhta hai transform → usi formula se data ko scale karta hai Why only train? Kyuki test data future ka data hai. Uska info pehle nahi lena.
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test) #only fit on train to avoid data leakage

#QUESTION ANSWERS
1. Why scaling is important?
ANS =  Because many machine learning algorithms are sensitive to feature magnitudes, and scaling prevents features with large values from dominating the model.

2. do every model needs scaling?
no tree based doesn't need.

In [24]:
#Model Training (Linear Regression) I used linear regression as a baseline

from sklearn.linear_model import LinearRegression
lr = LinearRegression()    #“I initialized the Linear Regression model.”
lr.fit(x_train_scaled , y_train)   #“The model learns the relationship between features and the target by minimizing error.”

LinearRegression()

#QUESTION ANSWERS
1. Why did you choose Linear Regression first?

Ans: Because it is simple, interpretable, and serves as a good baseline model.

2. What does fit() do?

Ans:It trains the model by learning coefficients from the training data.

3. What does the model actually learn?

Ans: It learns feature weights that best explain the target variable.

4.Can Linear Regression overfit?

Ans:Yes, especially when there are many features or multicollinearity.

In [25]:
y_pred = lr.predict(x_test_scaled)     #“I used the trained model to predict target values on the test dataset.”

#predict == ye ek function h jo har row ke liye formula lgata h har student ke liye ek predicted score nikalta h

#question answers
1. Why do we predict on test data, not training data?

To evaluate how the model performs on unseen data.

2. What is y_pred?

Answer:It contains the predicted values generated by the model.

3. Is prediction same as evaluation?

No. Prediction gives outputs, evaluation measures how good those outputs are.

In [29]:
#EVALUATION  how wrong it is predicting
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
mae = mean_absolute_error(y_test, y_pred)     #“MAE tells us the average absolute difference between actual and predicted values.”
mse = mean_squared_error(y_test, y_pred)     #“MSE penalizes larger errors more heavily.”
rmse = np.sqrt(mse)                           #“RMSE is preferred because it penalizes large errors and is in the same unit as the target variable.”
r2 = r2_score(y_test, y_pred)                 #“R² score shows how much variance in the target variable is explained by the model.”

print("MAE:" , mae)
print("MSE:", mae)
print("RMSE:", rmse)
print("r2 score:", r2)

MAE: 0.7650597682758259
MSE: 0.7650597682758259
RMSE: 1.2148700573987044
r2 score: 0.8486513286537314

#Questions answers
1. Which metric is best?

: It depends on the problem, but RMSE is commonly preferred for regression tasks.

2. High R² but high RMSE?

Answer:The model explains variance well but still makes large prediction errors.

3. Low R² always bad?

Answer: Not necessarily. It depends on data complexity and problem domain.

#I cleaned the data, encoded categorical variables, split the dataset, scaled features, trained a Linear Regression model, made predictions on unseen data, and evaluated the model using MAE, RMSE, and R² score.

In [30]:
#MODEL IMPROVEMENT
#DECISION TREE REGRESSOR

from sklearn.tree import DecisionTreeRegressor
dt = DecisionTreeRegressor(random_state = 42)      #i used decision tree to capture non linear patterns
dt.fit(x_train, y_train)                           #fit = learns rules and repeatedly splits data
y_pred_dt = dt.predict(x_test)                     # it apply learned rules, and predict test scores

In [33]:
#EVALUATION

mae_dt = mean_absolute_error(y_test , y_pred_dt)
rmse_dt = np.sqrt(mean_squared_error(y_test, y_pred_dt))
r2_dt = r2_score(y_test, y_pred)

print("MAE_DT : " , mae_dt)
print("RMSE_DT : ", rmse_dt)
print("R2_dt : ", r2_dt)

MAE_DT :  0.9230769230769231
RMSE_DT :  1.6501748159140361
R2_dt :  0.8486513286537314

#Question answers
1. Why Decision Tree after Linear Regression?

Linear Regression captures linear relationships, while Decision Trees can model non-linear patterns.

2. Why no scaling?

Answer: Tree-based models split on feature values, so scaling does not affect performance.

3. Risk of Decision Tree?

Answer: High risk of overfitting.

In [38]:
#RANDOM FOREST REGRESSOR >> Multiple Decision Trees ka group Har tree: Data ka thoda sa hissa dekhta hai Alag-alag rules seekhta hai Final output:Sab trees ka average prediction
from sklearn.ensemble import RandomForestRegressor
rf = RandomForestRegressor(n_estimators = 100,random_state = 42 )  #estimators=100 trees,random=reproducibility,i used 100 tress to reduce variance and improve generalzation
rf.fit(x_train, y_train)
y_pred_rf = rf.predict(x_test)

In [40]:
#EVALUATION

mae_rf = mean_absolute_error(y_test, y_pred_rf)
rmse_rf = np.sqrt(mean_squared_error(y_test, y_pred_rf))
r2_rf = r2_score(y_test, y_pred_rf)

print("MAE_RF : ", mae_rf)
print("RMSE_RF : ", rmse_rf)
print("R2_RF : " , r2_rf)

MAE_RF :  0.7460769230769232
RMSE_RF :  1.2408914289580448
R2_RF :  0.8420984017378219

#QUESTION ANSWERS
1. Why Random Forest?

Answer: It reduces overfitting by averaging multiple decision trees.

2. Why better than Decision Tree?

Answer: It generalizes better and is more stable.

3. Any drawback?

Answer: Less interpretable and more computationally expensive.

In [41]:
import pandas as pd

comparison = pd.DataFrame({
    "Model": ["Linear Regression", "Decision Tree", "Random Forest"],
    "MAE": [mae, mae_dt, mae_rf],
    "RMSE": [rmse, rmse_dt, rmse_rf],
    "R2 Score": [r2, r2_dt, r2_rf]
})

comparison

               Model       MAE      RMSE  R2 Score
0  Linear Regression  0.765060  1.214870  0.848651
1      Decision Tree  0.923077  1.650175  0.848651
2      Random Forest  0.746077  1.240891  0.842098

#Question answers

1. “Which model did you choose and why?”

 - “I compared Linear Regression, Decision Tree, and Random Forest using MAE, RMSE, and R² score. Random Forest performed best with the lowest error and highest R², so I selected it as the final model.”


2. “Why not Linear Regression?”

Answer: Linear Regression assumes linear relationships, while Random Forest captures complex non-linear patterns.

3. “Why not Decision Tree?”

Answer: Decision Tree tends to overfit, while Random Forest generalizes better.

#**EXPLANATION OF THE PROJECT**

**“I worked on a student performance regression project. I started with data cleaning and converted categorical variables using one-hot encoding. Then I split the data into training and testing sets and applied feature scaling for linear models.

I trained a Linear Regression model as a baseline, followed by Decision Tree and Random Forest models to capture non-linear relationships. I evaluated all models using MAE, RMSE, and R² score.

After comparison, Random Forest performed best with lower error and better generalization, so I selected it as the final model.”



“This project can be used by educational institutions to predict student performance in advance and identify students who may need academic support, enabling timely interventions and better resource allocation.”

Data comes from the system, the model predicts student performance in the backend, and the output is used to trigger academic interventions through dashboards.**